/* eslint-disable eslint-comments/no-unlimited-disable */

/* eslint-disable */

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as StreamedQueryRouteImport } from './routes/streamed-query'
import { Route as PaginationRouteImport } from './routes/pagination'
import { Route as InfiniteScrollingRouteImport } from './routes/infinite-scrolling'
import { Route as DedupingRouteImport } from './routes/deduping'
import { Route as BroadcastRouteImport } from './routes/broadcast'
import { Route as SuspenseQueryRouteRouteImport } from './routes/suspense-query/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SuspenseQueryIndexRouteImport } from './routes/suspense-query/index'
import { Route as PrefetchingIndexRouteImport } from './routes/prefetching/index'
import { Route as PollingIndexRouteImport } from './routes/polling/index'
import { Route as OptimisticUpdateCacheIndexRouteImport } from './routes/optimistic-update-cache/index'
import { Route as PollingNewTodoRouteImport } from './routes/polling/new-todo'
import { Route as PrefetchingIdIndexRouteImport } from './routes/prefetching/$id/index'
import { Route as OptimisticUpdateCacheIdIndexRouteImport } from './routes/optimistic-update-cache/$id/index'

const StreamedQueryRoute = StreamedQueryRouteImport.update({
  id: '/streamed-query',
  path: '/streamed-query',
  getParentRoute: () => rootRouteImport,
} as any)
const PaginationRoute = PaginationRouteImport.update({
  id: '/pagination',
  path: '/pagination',
  getParentRoute: () => rootRouteImport,
} as any)
const InfiniteScrollingRoute = InfiniteScrollingRouteImport.update({
  id: '/infinite-scrolling',
  path: '/infinite-scrolling',
  getParentRoute: () => rootRouteImport,
} as any)
const DedupingRoute = DedupingRouteImport.update({
  id: '/deduping',
  path: '/deduping',
  getParentRoute: () => rootRouteImport,
} as any)
const BroadcastRoute = BroadcastRouteImport.update({
  id: '/broadcast',
  path: '/broadcast',
  getParentRoute: () => rootRouteImport,
} as any)
const SuspenseQueryRouteRoute = SuspenseQueryRouteRouteImport.update({
  id: '/suspense-query',
  path: '/suspense-query',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SuspenseQueryIndexRoute = SuspenseQueryIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => SuspenseQueryRouteRoute,
} as any)
const PrefetchingIndexRoute = PrefetchingIndexRouteImport.update({
  id: '/prefetching/',
  path: '/prefetching/',
  getParentRoute: () => rootRouteImport,
} as any)
const PollingIndexRoute = PollingIndexRouteImport.update({
  id: '/polling/',
  path: '/polling/',
  getParentRoute: () => rootRouteImport,
} as any)
const OptimisticUpdateCacheIndexRoute =
  OptimisticUpdateCacheIndexRouteImport.update({
    id: '/optimistic-update-cache/',
    path: '/optimistic-update-cache/',
    getParentRoute: () => rootRouteImport,
  } as any)
const PollingNewTodoRoute = PollingNewTodoRouteImport.update({
  id: '/polling/new-todo',
  path: '/polling/new-todo',
  getParentRoute: () => rootRouteImport,
} as any)
const PrefetchingIdIndexRoute = PrefetchingIdIndexRouteImport.update({
  id: '/prefetching/$id/',
  path: '/prefetching/$id/',
  getParentRoute: () => rootRouteImport,
} as any)
const OptimisticUpdateCacheIdIndexRoute =
  OptimisticUpdateCacheIdIndexRouteImport.update({
    id: '/optimistic-update-cache/$id/',
    path: '/optimistic-update-cache/$id/',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/suspense-query': typeof SuspenseQueryRouteRouteWithChildren
  '/broadcast': typeof BroadcastRoute
  '/deduping': typeof DedupingRoute
  '/infinite-scrolling': typeof InfiniteScrollingRoute
  '/pagination': typeof PaginationRoute
  '/streamed-query': typeof StreamedQueryRoute
  '/polling/new-todo': typeof PollingNewTodoRoute
  '/optimistic-update-cache/': typeof OptimisticUpdateCacheIndexRoute
  '/polling/': typeof PollingIndexRoute
  '/prefetching/': typeof PrefetchingIndexRoute
  '/suspense-query/': typeof SuspenseQueryIndexRoute
  '/optimistic-update-cache/$id/': typeof OptimisticUpdateCacheIdIndexRoute
  '/prefetching/$id/': typeof PrefetchingIdIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/broadcast': typeof BroadcastRoute
  '/deduping': typeof DedupingRoute
  '/infinite-scrolling': typeof InfiniteScrollingRoute
  '/pagination': typeof PaginationRoute
  '/streamed-query': typeof StreamedQueryRoute
  '/polling/new-todo': typeof PollingNewTodoRoute
  '/optimistic-update-cache': typeof OptimisticUpdateCacheIndexRoute
  '/polling': typeof PollingIndexRoute
  '/prefetching': typeof PrefetchingIndexRoute
  '/suspense-query': typeof SuspenseQueryIndexRoute
  '/optimistic-update-cache/$id': typeof OptimisticUpdateCacheIdIndexRoute
  '/prefetching/$id': typeof PrefetchingIdIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/suspense-query': typeof SuspenseQueryRouteRouteWithChildren
  '/broadcast': typeof BroadcastRoute
  '/deduping': typeof DedupingRoute
  '/infinite-scrolling': typeof InfiniteScrollingRoute
  '/pagination': typeof PaginationRoute
  '/streamed-query': typeof StreamedQueryRoute
  '/polling/new-todo': typeof PollingNewTodoRoute
  '/optimistic-update-cache/': typeof OptimisticUpdateCacheIndexRoute
  '/polling/': typeof PollingIndexRoute
  '/prefetching/': typeof PrefetchingIndexRoute
  '/suspense-query/': typeof SuspenseQueryIndexRoute
  '/optimistic-update-cache/$id/': typeof OptimisticUpdateCacheIdIndexRoute
  '/prefetching/$id/': typeof PrefetchingIdIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/suspense-query'
    | '/broadcast'
    | '/deduping'
    | '/infinite-scrolling'
    | '/pagination'
    | '/streamed-query'
    | '/polling/new-todo'
    | '/optimistic-update-cache/'
    | '/polling/'
    | '/prefetching/'
    | '/suspense-query/'
    | '/optimistic-update-cache/$id/'
    | '/prefetching/$id/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/broadcast'
    | '/deduping'
    | '/infinite-scrolling'
    | '/pagination'
    | '/streamed-query'
    | '/polling/new-todo'
    | '/optimistic-update-cache'
    | '/polling'
    | '/prefetching'
    | '/suspense-query'
    | '/optimistic-update-cache/$id'
    | '/prefetching/$id'
  id:
    | '__root__'
    | '/'
    | '/suspense-query'
    | '/broadcast'
    | '/deduping'
    | '/infinite-scrolling'
    | '/pagination'
    | '/streamed-query'
    | '/polling/new-todo'
    | '/optimistic-update-cache/'
    | '/polling/'
    | '/prefetching/'
    | '/suspense-query/'
    | '/optimistic-update-cache/$id/'
    | '/prefetching/$id/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  SuspenseQueryRouteRoute: typeof SuspenseQueryRouteRouteWithChildren
  BroadcastRoute: typeof BroadcastRoute
  DedupingRoute: typeof DedupingRoute
  InfiniteScrollingRoute: typeof InfiniteScrollingRoute
  PaginationRoute: typeof PaginationRoute
  StreamedQueryRoute: typeof StreamedQueryRoute
  PollingNewTodoRoute: typeof PollingNewTodoRoute
  OptimisticUpdateCacheIndexRoute: typeof OptimisticUpdateCacheIndexRoute
  PollingIndexRoute: typeof PollingIndexRoute
  PrefetchingIndexRoute: typeof PrefetchingIndexRoute
  OptimisticUpdateCacheIdIndexRoute: typeof OptimisticUpdateCacheIdIndexRoute
  PrefetchingIdIndexRoute: typeof PrefetchingIdIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/streamed-query': {
      id: '/streamed-query'
      path: '/streamed-query'
      fullPath: '/streamed-query'
      preLoaderRoute: typeof StreamedQueryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagination': {
      id: '/pagination'
      path: '/pagination'
      fullPath: '/pagination'
      preLoaderRoute: typeof PaginationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/infinite-scrolling': {
      id: '/infinite-scrolling'
      path: '/infinite-scrolling'
      fullPath: '/infinite-scrolling'
      preLoaderRoute: typeof InfiniteScrollingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/deduping': {
      id: '/deduping'
      path: '/deduping'
      fullPath: '/deduping'
      preLoaderRoute: typeof DedupingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/broadcast': {
      id: '/broadcast'
      path: '/broadcast'
      fullPath: '/broadcast'
      preLoaderRoute: typeof BroadcastRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suspense-query': {
      id: '/suspense-query'
      path: '/suspense-query'
      fullPath: '/suspense-query'
      preLoaderRoute: typeof SuspenseQueryRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/suspense-query/': {
      id: '/suspense-query/'
      path: '/'
      fullPath: '/suspense-query/'
      preLoaderRoute: typeof SuspenseQueryIndexRouteImport
      parentRoute: typeof SuspenseQueryRouteRoute
    }
    '/prefetching/': {
      id: '/prefetching/'
      path: '/prefetching'
      fullPath: '/prefetching/'
      preLoaderRoute: typeof PrefetchingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polling/': {
      id: '/polling/'
      path: '/polling'
      fullPath: '/polling/'
      preLoaderRoute: typeof PollingIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optimistic-update-cache/': {
      id: '/optimistic-update-cache/'
      path: '/optimistic-update-cache'
      fullPath: '/optimistic-update-cache/'
      preLoaderRoute: typeof OptimisticUpdateCacheIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/polling/new-todo': {
      id: '/polling/new-todo'
      path: '/polling/new-todo'
      fullPath: '/polling/new-todo'
      preLoaderRoute: typeof PollingNewTodoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/prefetching/$id/': {
      id: '/prefetching/$id/'
      path: '/prefetching/$id'
      fullPath: '/prefetching/$id/'
      preLoaderRoute: typeof PrefetchingIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/optimistic-update-cache/$id/': {
      id: '/optimistic-update-cache/$id/'
      path: '/optimistic-update-cache/$id'
      fullPath: '/optimistic-update-cache/$id/'
      preLoaderRoute: typeof OptimisticUpdateCacheIdIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface SuspenseQueryRouteRouteChildren {
  SuspenseQueryIndexRoute: typeof SuspenseQueryIndexRoute
}

const SuspenseQueryRouteRouteChildren: SuspenseQueryRouteRouteChildren = {
  SuspenseQueryIndexRoute: SuspenseQueryIndexRoute,
}

const SuspenseQueryRouteRouteWithChildren =
  SuspenseQueryRouteRoute._addFileChildren(SuspenseQueryRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  SuspenseQueryRouteRoute: SuspenseQueryRouteRouteWithChildren,
  BroadcastRoute: BroadcastRoute,
  DedupingRoute: DedupingRoute,
  InfiniteScrollingRoute: InfiniteScrollingRoute,
  PaginationRoute: PaginationRoute,
  StreamedQueryRoute: StreamedQueryRoute,
  PollingNewTodoRoute: PollingNewTodoRoute,
  OptimisticUpdateCacheIndexRoute: OptimisticUpdateCacheIndexRoute,
  PollingIndexRoute: PollingIndexRoute,
  PrefetchingIndexRoute: PrefetchingIndexRoute,
  OptimisticUpdateCacheIdIndexRoute: OptimisticUpdateCacheIdIndexRoute,
  PrefetchingIdIndexRoute: PrefetchingIdIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
